autodetect: yes
strictness: medium
test-warnings: false
doc-warnings: true
ignore-paths:
  - tests
python-targets:
  - 2
  - 3
requirements:
  - setup.py
pep8:
  full: true  
pylint:
  full: true
pep257:
  full: true
