autodetect: yes
strictness: medium
test-warnings: false
doc-warnings: true
requirements:
  - setup.py
ignore-paths:
  - tests
ignore-patterns:
  - config.py
python-targets:
  - 2
  - 3
requirements:
  - setup.py
pep8:
  full: true
pylint:
  run: false
