autodetect: yes
strictness: medium
test-warnings: false
doc-warnings: true
ignore-paths:
  - tests
ignore-files:
  - config.py
python-targets:
  - 2
  - 3
requirements:
  - setup.py
pep8:
  full: true  
pylint:
  full: true
dodgy:
  full: true    
mccabe:
  full: true
