language: python
matrix:
  allow_failures:
    - os: osx
  include:
    - os: linux
      sudo: required
      python: 3.5
    - os: linux
      sudo: required
      python: 3.6
    - os: osx
      language: generic
      env: TRAVIS_OS_NAME=osx
# python:
#   - "3.5"
#   - "3.6"
# command to install dependencies
services:
  - postgresql 
  - elasticsearch
  - docker
addons:
  postgresql: "9.5"  
  apt:
    packages:
      - docker-ce
before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install python3; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install elasticsearch; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew postinstall python3; fi
  - docker build -t travis/gykernel -f Dockerfile.gykernel .
  - docker run --name=gykernel -d -it -p 7000:7000 travis/gykernel
  - docker ps -a
cache: pip
install:
  - pip3 install -r requirements.txt
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rm -rf /usr/local/var/postgres; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then initdb /usr/local/var/postgres; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pg_ctl -D /usr/local/var/postgres start; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then createuser -s postgres; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew services start elasticsearch; fi
  - sleep 10
  - createuser -s -w -U postgres -e capivara
  - createdb green_eyes -U capivara
  - psql -c "ALTER USER capivara WITH PASSWORD 'test';" -U postgres
  - psql -U capivara green_eyes < backupGreeneyes.sql
  - psql -U capivara green_eyes < missingSQL.sql  
  - export PYTHONPATH=$PYTHONPATH:$(pwd)  
# command to run tests
script:
  - coverage run --source=api setup.py test  
after_script:
  - kill $!
after_success:
  - coveralls
