language: python
matrix:
  allow_failures:
    - os: osx
  include:
    - os: linux
      sudo: required
      python: 3.5
    - os: linux
      sudo: required
      python: 3.6
# command to install dependencies
services:
  - postgresql 
  - elasticsearch
  - docker
  - rabbitmq
addons:
  postgresql: "9.5"  
  apt:
    packages:
      - docker-ce
before_install:
  - docker run --name=gykernel -d -it -p 7000:7000 capivaraprojects/gykernel
cache: pip
install:
  - pip3 install -r requirements.txt
before_script:
  - celery -A api.gyresources.logic.tf_serving_client worker --loglevel=info &
  - createuser -s -w -U postgres -e capivara
  - createdb green_eyes -U capivara
  - psql -c "ALTER USER capivara WITH PASSWORD 'test';" -U postgres
  - psql -U capivara green_eyes < backupGreeneyes.sql
  - export PYTHONPATH=$PYTHONPATH:$(pwd)  
  - sleep 5
# command to run tests
script:
  - travis_wait 25 coverage run --source=api setup.py test
after_success:
  - coveralls
