language: python
matrix:
    include:
        - os: linux
          sudo: required
          python: 3.5
        - os: linux
          sudo: required
          python: 3.6
        - os: osx
          language: generic
          env: TRAVIS_OS_NAME=osx
# python:
#   - "3.5"
#   - "3.6"
# command to install dependencies
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx"]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"]]; then brew install python3; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"]]; then brew postinstall python3; fi
cache: pip
install:
  - pip3 install -r requirements.txt
services:
  - postgresql 
  - elasticsearch
addons:
  postgresql: "9.5"  
before_script:
  - sleep 10
  - createuser -s -w -U postgres -e capivara
  - createdb green_eyes -U capivara
  - psql -c "ALTER USER capivara WITH PASSWORD 'test';" -U postgres
  - psql -U capivara green_eyes < backupGreeneyes.sql
  - psql -U capivara green_eyes < missingSQL.sql  
  - export PYTHONPATH=$PYTHONPATH:$(pwd)  
# command to run tests
script:
  - coverage run --source=api setup.py test  
after_success:
  - coveralls
