language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
cache: pip
install:
  - pip3 install -r requirements.txt
services:
  - postgresql 
  - elasticsearch
addons:
  postgresql: "9.5"  
before_script:
  - sleep 10
  - createuser -s -w -U postgres -e capivara
  - createdb green_eyes -U capivara
  - psql -c "ALTER USER capivara WITH PASSWORD 'test';" -U postgres
  - psql -U capivara green_eyes < backupGreeneyes.sql
  - psql -U capivara green_eyes < missingSQL.sql  
  - export PYTHONPATH=$PYTHONPATH:$(pwd)  
# command to run tests
script:
  - coverage run --source=api setup.py test  
after_success:
  - coveralls
