sut:
  build: .
  environment:
    - PYTHONPATH=${PYTHONPATH}
  command: /etc/init.d/postgresql start && /etc/init.d/elasticsearch start && /etc/init.d/rabbitmq-server start && zsh -c "celery -A api.gyresources.logic.tf_serving_client worker --loglevel=info &!" && sleep 5 && python3 setup.py test
