INSERT INTO TEXTS(language, plant, status, attribute, value, reference) VALUES ('pt-br', 'Tomato', 'Alternaria solani', 'commom_name', 'Pinta-preta, mancha-de-Alternaria', 'http://agrofit.agricultura.gov.br/agrofit_cons/!ap_praga_detalhe_cons?p_id_cultura_praga=4751');
INSERT INTO TEXTS(language, plant, status, attribute, value, reference) VALUES ('pt-br', 'Tomato', 'Alternaria solani', 'description', 'A mancha-de-Alternaria é uma das doenças mais importantes do tomateiro, causando grandes perdas. É uma doença encontrada em vários lugares do mundo, e no Brasil está presente em todas as regiões produtoras de tomate. A doença ataca todas as partes aéreas da planta, debilitando-a. Os frutos são atacados diretamente, o que causa a perda total dos mesmos.', 'http://agrofit.agricultura.gov.br/agrofit_cons/!ap_praga_detalhe_cons?p_id_cultura_praga=4751');
INSERT INTO TEXTS(language, plant, status, attribute, value, reference) VALUES ('pt-br', 'Tomato', 'Alternaria solani', 'symptom', 'As plantas apresentam manchas marrom-escuras na superfície das folhas mais velhas, quando o ataque é muito severo, as manchas se unem fortemente ocupando quase toda a lâmina foliar, provocando a secagem das folhas, e os frutos ficam expostos ao sol, sofrendo queimaduras severas. No fruto o ataque ocorre principalmente na região peduncular dos frutos maduros, produzindo uma podridão escura chamada de mofo-preto; no interior da mancha observam-se também os anéis concêntricos típicos da doença.No caule manchas arredondadas ou elípticas, marrons, mais claras que nas folhas, e no seu interior formam-se também os característicos anéis.', 'http://agrofit.agricultura.gov.br/agrofit_cons/!ap_praga_detalhe_cons?p_id_cultura_praga=4751');
INSERT INTO TEXTS(language, plant, status, attribute, value, reference) VALUES ('pt-br', 'Tomato', 'Alternaria solani', 'bioecology', 'O patógeno pode sobreviver por longos períodos no solo, sobre os restos de colheita ou sobre as plantas voluntárias e nas hospedeiras alternativas que crescem no próprio campo ou na vegetação nativa da vizinhança. Geralmente, o fungo produz grande quantidade de clamidósporos nos restos culturais, responsáveis pela longevidade do inóculo no solo. As sementes contaminam-se facilmente com os esporos do fungo, sendo uma das vias de disseminação da doença a grandes distâncias. Mudas originadas de sementes contaminadas são também uma via importante para a disseminação da doença. Dentro do campo, o patógeno é dispersado pelo vento, respingos da chuva, água de irrigação, insetos, roupa ou mãos dos operários e implementos agrícolas. Temperatura (26-30 °C) e umidade altas durante o verão chuvoso, alta carga de frutos e solo pobre em nitrogênio favorecem o desenvolvimento da doença. Também ocorre no inverno, quando as temperaturas são relativamente altas e a umidade relativa é elevada, principalmente por excesso de irrigação.', 'http://agrofit.agricultura.gov.br/agrofit_cons/!ap_praga_detalhe_cons?p_id_cultura_praga=4751');
INSERT INTO TEXTS(language, plant, status, attribute, value, reference) VALUES ('pt-br', 'Tomato', 'Alternaria solani', 'control', 'É essencial o uso de sementes livres do patógeno, tratadas adequadamente com fungicidas.Deve-se efetuar rotações de culturas, eliminar os restos culturais infectados no final da colheita, controlar as plantas voluntárias e as solanáceas daninhas. As plantações devem ser feitas em áreas arejadas, onde não seja freqüente a formação de orvalho, e irrigar só quando necessário.', 'http://agrofit.agricultura.gov.br/agrofit_cons/!ap_praga_detalhe_cons?p_id_cultura_praga=4751');


INSERT INTO TEXTS(language, plant, status, attribute, value, reference) VALUES ('pt-br', 'Tomato', 'Tetranychus urticae', 'commom_name', 'Ácaro-rajado', 'http://agrofit.agricultura.gov.br/agrofit_cons/!ap_praga_detalhe_cons?p_id_cultura_praga=3578');
INSERT INTO TEXTS(language, plant, status, attribute, value, reference) VALUES ('pt-br', 'Tomato', 'Tetranychus urticae', 'description', 'Os insetos deste gênero pertencem a um grupo de ácaros que causam danos a várias espécies de plantas. Esta espécie ocorre em várias culturas de importância econômica, como abóbora, algodão, amendoim, berinjela, crisântemo, feijão, maçã, mamão, mamona, melancia, melão, morango, pepino, pêra, pêssego, pimentão, rosa e tomate.', 'http://agrofit.agricultura.gov.br/agrofit_cons/!ap_praga_detalhe_cons?p_id_cultura_praga=3578');
INSERT INTO TEXTS(language, plant, status, attribute, value, reference) VALUES ('pt-br', 'Tomato', 'Tetranychus urticae', 'symptom', 'Ao sugarem as folhas, aparecem manchas amareladas que, com o passar do tempo, tornam-se pardo-avermelhadas. Ocorre definhamento das plantas e queda na produção. O fruto atacado fica endurecido, seco e com coloração marrom.', 'http://agrofit.agricultura.gov.br/agrofit_cons/!ap_praga_detalhe_cons?p_id_cultura_praga=3578');
INSERT INTO TEXTS(language, plant, status, attribute, value, reference) VALUES ('pt-br', 'Tomato', 'Tetranychus urticae', 'bioecology', 'São ácaros verdes, com quatro pares de patas. Formam colônias e tecem teias entre as nervuras das folhas mais velhas. A colônia tem aspecto pardo. As fêmeas apresentam duas manchas verde-escuras no dorso e são maiores que os machos.', 'http://agrofit.agricultura.gov.br/agrofit_cons/!ap_praga_detalhe_cons?p_id_cultura_praga=3578');
INSERT INTO TEXTS(language, plant, status, attribute, value, reference) VALUES ('pt-br', 'Tomato', 'Tetranychus urticae', 'control', 'Controle químico: fazer uso de inseticidas específicos, conforme recomendação', 'http://agrofit.agricultura.gov.br/agrofit_cons/!ap_praga_detalhe_cons?p_id_cultura_praga=3578');

INSERT INTO TEXTS(language, plant, status, attribute, value, reference) VALUES ('pt-br', 'Tomato', 'Xanthomonas vesicatoria', 'commom_name', 'Mancha-bacteriana', 'http://agrofit.agricultura.gov.br/agrofit_cons/!ap_praga_detalhe_cons?p_id_cultura_praga=4639');
INSERT INTO TEXTS(language, plant, status, attribute, value, reference) VALUES ('pt-br', 'Tomato', 'Xanthomonas vesicatoria', 'description', 'A mancha-bacteriana causada por Xanthomonas versicatoria (ex Doidge) Vauterin, Hoste, Kersters (sinônimo: Xanthomonas campestris (Pammel) Dowson pv. versicatoria (Doidge) Dye et al.) é uma bacteriose importante economicamente para a cultura do tomate, podendo causar perdas de até 30% na produção de frutos.Esta bactéria ocorre também em berinjela, jiló, pimenta e pimentão.', 'http://agrofit.agricultura.gov.br/agrofit_cons/!ap_praga_detalhe_cons?p_id_cultura_praga=4639');
INSERT INTO TEXTS(language, plant, status, attribute, value, reference) VALUES ('pt-br', 'Tomato', 'Xanthomonas vesicatoria', 'symptom', 'A bactéria pode ocorrer em todos os estágios de desenvolvimento da planta.Nas folhas são observadas manchas encharcadas, distribuídas principalmente nas bordas da folha. Essas manchas tornam-se necróticas e podem coalescer. Podem ocorrer lesões de coloração marrom no caule. Nos frutos as lesões são esbranquiçadas, tornando-se marrons, deprimidas, com aparência áspera e presença de halos encharcados, de cor verde. Quando a infecção ocorre em frutos novos, causa deformação e queda.', 'http://agrofit.agricultura.gov.br/agrofit_cons/!ap_praga_detalhe_cons?p_id_cultura_praga=4639');
INSERT INTO TEXTS(language, plant, status, attribute, value, reference) VALUES ('pt-br', 'Tomato', 'Xanthomonas vesicatoria', 'bioecology', 'A bactéria Xanthomonas versicatoria possui baixa capacidade de sobrevivência em restos culturais nas condições brasileiras, porém sobrevive eficientemente em sementes. A disseminação a longas distâncias ocorre por meio de sementes e mudas doentes, e dentro de uma mesma área por meio de respingos de água da chuva e/ou da irrigação e durante os tratos culturais. De planta a planta a disseminação pode ocorrer ainda pelo contato direto entre folhas. Temperaturas entre 22 e 28 °C e umidade relativa entre 95 e 100%, com presença de água livre, são condições favoráveis à penetração da bactéria, que se dá através das aberturas naturais ou por ferimentos provocados.', 'http://agrofit.agricultura.gov.br/agrofit_cons/!ap_praga_detalhe_cons?p_id_cultura_praga=4639');
INSERT INTO TEXTS(language, plant, status, attribute, value, reference) VALUES ('pt-br', 'Tomato', 'Xanthomonas vesicatoria', 'control', 'Práticas culturais: Para o plantio é indispensável o uso de sementes e mudas sadias e de boa qualidade, assim como máquinas e equipamentos limpos. A irrigação deve ser manejada de modo a não favorecer a presença d água livre sobre as plantas. Deve-se realizar rotação de cultura com espécies não hospedeiras por 1 a 2 anos. Controle químico: A aplicação de fungicidas cúpricos em caso de ocorrência no campo, é outra possibilidade de controle.', '');

INSERT INTO TEXTS(language, plant, status, attribute, value, reference) VALUES ('pt-br', 'Tomato', 'Septoria lycopersici', 'commom_name', 'Septoriose, pinta-preta-pequena', 'http://agrofit.agricultura.gov.br/agrofit_cons/!ap_praga_detalhe_cons?p_id_cultura_praga=4639');
INSERT INTO TEXTS(language, plant, status, attribute, value, reference) VALUES ('pt-br', 'Tomato', 'Septoria lycopersici', 'description', 'A septoriose ou pinta-preta-pequena, causada pelo fungo Septoria lycopersici Speg., ocorre em todos os locais de cultura de tomate no mundo. Esta é uma doença de grande importância econômica não só pelo fato de estar amplamente distribuída, mas também por ser muito destrutiva, causando perdas que podem chegar a 100%.', 'http://agrofit.agricultura.gov.br/agrofit_cons/!ap_praga_detalhe_cons?p_id_cultura_praga=4639');
INSERT INTO TEXTS(language, plant, status, attribute, value, reference) VALUES ('pt-br', 'Tomato', 'Septoria lycopersici', 'symptom', 'A septoriose pode ocorrer em qualquer estágio de desenvolvimento da planta. Nas folhas os primeiros sintomas são manchas pequenas, encharcadas, de formato circular, que ocorrem na face inferior das folhas, principalmente nas folhas baixeiras mais velhas. Com a evolução da doença, as manchas se tornam circulares, a região central se torna acinzentada e a borda marrom-escura. As manchas podem coalescer, adquirindo um formato irregular.Na região central das lesões podem ser facilmente observadas estruturas de cor preta, que são as estruturas de frutificação do fungo (picnídios).Folhas severamente atacada amarelecem, podendo ocorrer desfolha progressiva de baixo para cima.Geralmente, os frutos produzidos em plantas severamente desfolhadas são pequenos, além de apresentarem queimadura devido à exposição direta ao sol.', 'http://agrofit.agricultura.gov.br/agrofit_cons/!ap_praga_detalhe_cons?p_id_cultura_praga=4639');
INSERT INTO TEXTS(language, plant, status, attribute, value, reference) VALUES ('pt-br', 'Tomato', 'Septoria lycopersici', 'bioecology', 'Septoria lycopersici é capaz de sobreviver em sementes, hospedeiros alternativos e restos culturais, que são a principal fonte de inóculo inicial. A dispersão ocorre por meio da água de chuva e/ou de irrigação, trabalhadores e implementos agrícolas durante os tratos culturais e insetos que carregam os conídios do fungo, os quais são produzidos dentro dos picnídios em condições de umidade elevada. Longos períodos de umidade relativa elevada, temperaturas amenas e chuvas abundantes são condições ideais para o desenvolvimento da doença e disseminação do fungo.', 'http://agrofit.agricultura.gov.br/agrofit_cons/!ap_praga_detalhe_cons?p_id_cultura_praga=4639');
INSERT INTO TEXTS(language, plant, status, attribute, value, reference) VALUES ('pt-br', 'Tomato', 'Septoria lycopersici', 'control', 'Práticas culturais: Deve-se eliminar as fontes de inóculo inicial através da remoção e destruição dos restos culturais e da rotação de cultura com espécies não hospedeiras. Para o plantio devem-se utilizar mudas sadias. Irrigação por aspersão não é recomendada.Controle químico: Fungicidas protetores e sistêmicos são efetivos no controle da septoriose.', 'http://agrofit.agricultura.gov.br/agrofit_cons/!ap_praga_detalhe_cons?p_id_cultura_praga=4639');

INSERT INTO TEXTS(language, plant, status, attribute, value, reference) VALUES ('pt-br', 'Tomato', 'healthy', 'control', 'scientific_name', 'Lycopersicum esculentum', 'https://pt.wikipedia.org/wiki/Tomate');
INSERT INTO TEXTS(language, plant, status, attribute, value, reference) VALUES ('pt-br', 'Tomato', 'healthy', 'commom_name', 'Tomate', 'https://pt.wikipedia.org/wiki/Tomate');
INSERT INTO TEXTS(language, plant, status, attribute, value, reference) VALUES ('pt-br', 'Tomato', 'healthy', 'description', 'Pertencente à família Solanaceae, o tomate é um fruto gerado a partir da fecundação da flor do tomateiro. O tomate não é uma hortaliça, como muitos pensam erroneamente. O fruto possui a polpa carnosa, suculenta e cheia de sementes, por isso é muito usado em saladas, para o preparo de molhos, no recheio de sanduíches e tortas ou mesmo como ingrediente de sopas e sucos.', 'https://www.portalagropecuario.com.br/agricultura/informacoes-a-respeito-do-cultivo-de-tomate/');
INSERT INTO TEXTS(language, plant, status, attribute, value, reference) VALUES ('pt-br', 'Tomato', 'healthy', 'culture', 'O plantio deve ter início com a produção de mudas em bandejas de isopor. O produtor precisa molhar as plantinhas diariamente durante essa fase. As bandejas devem ser mantidas em local protegido para evitar o ataque de pragas e insetos. Assim que as mudas apresentarem quatro ou cinco folhas, ou atingirem a altura de sete a dez centímetros, elas devem ser transplantadas para o local definitivo. A colheita pode ser feita depois de 90 a 100 dias do transplante, pois o tomateiro já estará com muitos ramos e caule flexível. Como o tomate tem a característica de continuar amadurecendo mesmo fora do pé, ele pode ser colhido ainda verde.', 'https://www.portalagropecuario.com.br/agricultura/informacoes-a-respeito-do-cultivo-de-tomate/');
INSERT INTO TEXTS(language, plant, status, attribute, value, reference) VALUES ('pt-br', 'Tomato', 'healthy', 'ground', 'Terreno deve ser profundo, permeável, solto, bem drenado, areno-argiloso e com pH entre 5,5 e 6,5. É importante manter o terreno sempre úmido.', 'https://www.portalagropecuario.com.br/agricultura/informacoes-a-respeito-do-cultivo-de-tomate/');
INSERT INTO TEXTS(language, plant, status, attribute, value, reference) VALUES ('pt-br', 'Tomato', 'healthy', 'season', 'O tomate pode ser plantado o ano todo, desde que o clima da região seja ameno. Temperaturas muito baixas ou calor excessivo prejudicam o desenvolvimento e a produção do tomateiro. Contudo, caso não haja como fugir destes climas, recomenda-se o plantio entre os meses de agosto e janeiro em locais frios e entre março e maio em locais de temperatura muito elevada.', 'https://www.portalagropecuario.com.br/agricultura/informacoes-a-respeito-do-cultivo-de-tomate/');
INSERT INTO TEXTS(language, plant, status, attribute, value, reference) VALUES ('pt-br', 'Tomato', 'healthy', 'weather', 'O tomateiro se dá bem em locais com condições climáticas variadas, mas com poucas chuvas.', 'https://www.portalagropecuario.com.br/agricultura/informacoes-a-respeito-do-cultivo-de-tomate/');
